[package]
name = "bufr-read"
version = "0.2.6"
authors = ["Ryan <rnleach@users.noreply.github.com>"]
edition = "2018"
publish = false

[dependencies]
eccodes-sys = {version = "2.19.1", git = "https://github.com/rnleach/eccodes-sys.git", tag="v2.19.1"}
libc = "0.2"
optional = "0.5"
